### ISSUE TITLE
Doesn't work with Stanford 3.5.2

### ISSUE THREAD

**Issue by kevinheffernan** [vpekar/stanford-parser-in-jython#3]
headTagNode seems to have been removed in version 3.5.2 resulting in the error:

'edu.stanford.nlp.trees.TreeGraphNode' object has no attribute 'headTagNode'
